### PR TITLE
revamp with .net 8

### LINKED ISSUE #17: Implement strong entropy shim for non-browser environments
Starting with .NET 6 the runtime uses native platform API to generate random numbers: https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid?view=net-6.0#remarks

In browser `crypto.getRandomValues` is [utilized by the runtime](https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/Native/Unix/System.Native/pal_random.js#L27) and for other environments we are using a naive `Math.random` shim at the moment: https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-runtime/src/mono.ts#L39

As mentioned in the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random), the function does not provide cryptographically secure random numbers.

While it's probably not possible (?) to implement proper strong entropy generation without access to the native APIs, we have to at least improve current naive solution.

Related: #2

### LINKED ISSUE #19: Support .NET -> JavaScript streaming
While Blazor provide APIs for raw byte streaming between .NET and JavaScript ([doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-net-to-javascript)), .NET to JS streaming relies on browser-only `Response` type:

https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-js-interop/src/main.js#L458

Associated calls in the runtime:
https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Components/Web.JS/src/GlobalExports.ts#L80
https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Components/Web.JS/src/StreamingInterop.ts#L24

We have to add environment-agnostic streaming implementation and test it:
https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-runtime/test/interop.js#L125

### LINKED ISSUE #20: Migrate to stock .NET runtime
We are currently using a [custom .NET runtime build](https://github.com/Elringus/DotNetUMD) and [JS wrapper post-processing](https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-runtime/scripts/compile-runtime.sh#L13) to support webpack UMD target. This limits the options when building the projects, such as AOT and module trimming.

There is an on-going work at the .NET runtime main branch to modularize the WASM runtime and make it work outside of browser, eg:
https://github.com/dotnet/runtime/pull/61313
https://github.com/dotnet/runtime/pull/62292
https://github.com/dotnet/runtime/issues/47336

At some point, it may become possible to use the module distributed with the runtime SDK, which will resolve the limitations.

If someone happen to know an alternative solution to make current (.NET 6) WASM compatible with UMD target, please let us know here. Sharing updates regarding changes in the .NET runtime that could help with the issue is also appreciated. 

-----
Currently blocked by:
 - https://github.com/dotnet/roslyn/issues/57239 (via https://github.com/Elringus/DotNetJS/issues/75)
 - https://github.com/dotnet/runtime/issues/80045
 - https://github.com/dotnet/runtime/issues/86162

### LINKED ISSUE #22: Research .NET runtime WASM module lifecycle
It is not clear whether the .NET runtime WASM module have to be terminated and/or if it can be re-initialized.

There appears to be `emscripten_force_exit` function in the module, but it throws an error:
https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-runtime/src/wasm.ts#L25

Is someone have any related info, please let us know here.

### LINKED ISSUE #23: Solve the non-entry assembly loading mystery
Given there are multiple assemblies that require JavaScript interop (contain`[JSInvokable]` or `[JSFunction]` attributed methods), only the entry assembly is loaded, while when trying to invoke methods from the others, `Assembly not loaded` exception is thrown.

We are currently using following hack to force-load such assemblies:
https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-runtime/test/csharp/Test.Main/Program.cs#L31

If the hack is removed, the JS tests that use methods from `Test.Types` assembly will fail.

We have to figure if that's by design and/or find a more elegant way to force-load the assemblies.

If someone have any related info, please let us know here.

### LINKED ISSUE #26: Throw meaningful error when JavaScript function is not implemented
Currently, when a `[JSFunction]`-attributed method is invoked while the associated function is not implemented in JavaScript, a `JSException` is thrown, but without any message to identify reason of the error: https://github.com/Elringus/DotNetJS/blob/f44665a9b7b4259d13469ef5ea928c7cdb6caff1/JavaScript/dotnet-runtime/test/packed.js#L26

We've tried initializing the bindings with `function (...args) { throw Error("..."); }` instead of `undefined`: https://github.com/Elringus/DotNetJS/blob/f44665a9b7b4259d13469ef5ea928c7cdb6caff1/DotNet/Packer/LibraryGenerator.cs#L71

— hoping the message will be propagated back to JavaScript, but .NET runtime throws back just the exception name with stacktrace and, more importantly, the runtime fails to invoke the function after such throw, even if it's assigned.

If anyone have any idea on how this can be solved, please let us know here.

### LINKED ISSUE #51: Git rid of eval() in WASM wrapper
Hi again!
I used DotNetJS to create a library that exposes some common functions that we share across C# executables and an Electron app to ensure the behaviour is identical.
The problem is, the electron's app ([Vortex](https://github.com/Nexus-Mods/Vortex)) is blocking `eval` execution due to it's CSP. I did earlier some investigation about this, but I would like to double check! Is `eval` critical for the runtime to work or is it used only for debugging? Could we strip it's usage with some conditionals?

- [x] Waiting for https://github.com/dotnet/runtime/pull/74441

### LINKED ISSUE #53: Support ES module import in browser
Hi again, 

I tested the library with angular and it is running into an error: 
```bash
universalModuleDefinition:1 Uncaught ReferenceError: global is not defined
    at universalModuleDefinition:1:1
    at Object.9424 (universalModuleDefinition:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.1896 (home.component.html:14:263)
    at __webpack_require__ (bootstrap:19:1)
    at Module.721 (universalModuleDefinition:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.23 (app.component.html:6:8)
    at __webpack_require__ (bootstrap:19:1)
    at Module.8835 (environment.ts:16:71)
```

Which is expected as the angular team came to the conclusion to not support global in their webpack build for broad compatibility. https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

I think this library should not rely on some other process to supply the variable.
So going forward you could use: 
- globalThis: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
- polyfill it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#search_for_the_global_across_environments

Workaround is adding `(window as any).global = window;` to `polyfill.ts`

### LINKED ISSUE #72: Detect when to emit nullable defines in auto-generated C# files
Due to #68 compiler now require `#nullable enable` defines when nullable reference type annotations are used in the auto-generated files.

I'm not aware of a reliable way to detect whether a nullable annotation is used in the analyzed syntax tree, so the generators always emit `#nullable` defines (#71), which could cause issues when the consumer doesn't have nullable reference types enabled.

If anyone have any idea how to detect whether the nullable define should be emitted (eg, by checking whether a nullable annotation is used anywhere in the analyzed syntax tree):

https://github.com/Elringus/DotNetJS/blob/1c11d8c8ac71d786fde85dad82f3c45a16f07f9a/DotNet/Generator/GeneratedClass.cs#L19-L21

— please let us know here.

### LINKED ISSUE #75: Migrate to the new JS interop layer
It looks like at some point (.NET 7?) a new JS interop layer will be introduced: 

 - https://github.com/dotnet/runtime/pull/66304
 - https://github.com/dotnet/runtime/pull/71332

### LINKED ISSUE #79: Support multithreading
Once multi-threading is available in .NET's wasm-browser, add an option to enable it with the packager.

Tracking: https://github.com/dotnet/runtime/issues/68162

### LINKED ISSUE #112: Error when publishing to custom output path
Publishing with `-o, --output <OUTPUT_DIR>` option breaks the `PublishDotNetJS` task.

```csproj
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="DotNetJS" Version="0.23.1" />
	</ItemGroup>
</Project>
```
```csharp
using Microsoft.JSInterop;

Console.WriteLine("Hello, World!");

[JSInvokable]
static string Test(string value) => value;
```
```
 dotnet publish -c "Release" -o "D:\ExampleApp\.deploy\test"
```
```
...\DotNetJS.targets(23,9): error MSB4018: The "PublishDotNetJS" task failed unexpectedly.
...\DotNetJS.targets(23,9): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ExampleApp\ExampleApp\bin\Release\net6.0\publish\wwwroot\_framework'.
...\DotNetJS.targets(23,9): error MSB4018:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
...\DotNetJS.targets(23,9): error MSB4018:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
...\DotNetJS.targets(23,9): error MSB4018:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
...\DotNetJS.targets(23,9): error MSB4018:    at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
...\DotNetJS.targets(23,9): error MSB4018:    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTargetsearchTarget, EnumerationOptions options)
...\DotNetJS.targets(23,9): error MSB4018:    at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
...\DotNetJS.targets(23,9): error MSB4018:    at Packer.TypeUtilities.CreateLoadContext(String directory)
...\DotNetJS.targets(23,9): error MSB4018:    at Packer.NamespaceBuilder.CollectConverters(String outDir, String entryAssembly)
...\DotNetJS.targets(23,9): error MSB4018:    at Packer.PublishDotNetJS.CreateNamespaceBuilder()
...\DotNetJS.targets(23,9): error MSB4018:    at Packer.PublishDotNetJS.GenerateSources()
...\DotNetJS.targets(23,9): error MSB4018:    at Packer.PublishDotNetJS.Execute()
...\DotNetJS.targets(23,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
...\DotNetJS.targets(23,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask
```

### PR DESCRIPTION
**Pull request by elringus**
Complete rewrite using improved .NET 8 WASM capabilities and new JavaScript interop.

## Changed
- Package name changed to Bootsharp.
- All the package-specific MSBuild properties got "Bootsharp" prefix to prevent conflicts; eg `BootsharpEmbedBinaries`.
- `Event.getLast()` changed to `Event.last`.
- Enums are now serialized as numbers by default (prev. strings). This can be changed via `Bootsharp.Serializer.Options` in C#. Enum names can still be accessed in JS, eg:
   ​​​​​​​
  ```cs
  enum MyEnum { Foo, Bar } // C#
  ```
  ```js
  MyEnum[MyEnum.Foo] === "Foo" // JS
  ```

## Improved
- The package now uses stock .NET runtime. (resolves #20, resolves #17)
- Multithreading is now supported.  (resolves #79)
- AOT compilation is now supported. Package itself is now completely free of dynamic code and fully AOT-compatible.
- Trimming is now supported. With aggressive trimming enabled, minimal compressed build size is 744 KB.
- Stream-compiling WASM module is now supported.
- ES module is now produced instead of UMD, providing support for modern consumption scenarios in both browsers and JavaScript runtimes (node, [deno](https://deno.com), [bun](https://bun.sh) and VS Code [web extension](https://code.visualstudio.com/api/extension-guides/web-extensions) were tested). (resolves #53)
- Internal JSON serializer now works in source generation mode and doesn't use reflection.
- New JavaScript interop doesn't use reflection and allows direct transfer of common data types (byte, int, bool, char, string and arrays of them); only custom data structures are serialized to JSON. (resolves #75, resolves #51, resolves #19)
- Added extensions on `Microsoft.Extensions.DependencyInjection` for automatic injection and instantiation of the generated interop implementations (via standalone package).
- `Event.last` now returns all the arguments of the last broadcast (previously returned only the first one).
- When invoking a C# API while the runtime is not booted or invoking JavaScript binding which has not been assigned, an error with the endpoint is thrown. (resolves #26)

## Fixed
- Publishing to custom output path. (fixes #112)
- Defining bindings in non-entry assemblies. (fixes #23)
- Disposing runtime WASM module resources. (fixes #22)

### CODE REVIEW

**Comment by Aragas** [comment]
Any ETA on the merge?

**Comment by elringus** [comment]
> Any ETA on the merge?

Hopefully by the end of the year. Planned to finish before .NET 8 GA, but got distracted with a side hustle. Though, it's already fully functional: I've migrated my own projects and everything seem to be working fine. Here are the latest packages if you'd like to try it out: [bootsharp.zip](https://github.com/elringus/DotNetJS/files/13437396/Bootsharp.zip).

**Comment by Aragas** [comment]
> Hopefully by the end of the year. Planned to finish before .NET 8 GA, but got distracted with a side hustle. Though, it's already fully functional: I've migrated my own projects and everything seem to be working fine. Here are the latest packages if you'd like to try it out: [bootsharp.zip](https://github.com/elringus/DotNetJS/files/13437396/Bootsharp.zip).

Thanks for the packages! I was able to test the generation, but I'm not sure if it generated the desired outcome. Basically, it generates `bin\Debug\net8.0\browser-wasm\AppBundle`, but using `BootsharpPackageDirectory` for a custom path where the end package should be copied seems not to work.
Should the outcome be similar to what we had previously? The typescript declaration for the package and the wasm files?

**Comment by elringus** [comment]
Yes, it should be similar to how it's worked before. Check the samples: https://github.com/elringus/DotNetJS/tree/feat/revamp/Samples

**Comment by Problemkurs** [comment]
Many thanks for your effort. I'm amazed how you got this working as there is not much information available I found. 

I have an issue when publishing a project with bootsharp: After sucessful compilation the process exists with error code "npx rollup bootsharp.js -o bootsharp.mjs -f es -g process,module --output.inlineDyn
amicImports" + another message "Cannot find module 'node:process'". This happens when I build the samples (ex. Trimming ) as well as in my own projects I tried it with. Any idea what this might be?

**Comment by elringus** [comment]
@Problemkurs Make sure node v20 or later is in the system path. (https://nodejs.org)

**Pull request merged**
